config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands do
    resources :albums, only: [:index, :show] do
      resources :tracks, only: [:index, :show]
    end
  end

  resources :albums, except: :index # change
  resources :tracks, except: :index do # change
    resources :notes, only: [:show, :new, :create, :destroy]
  end

  resources :users do
    get "activate"
  end
  resource :session

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :name, :album_id, :regular_or_bonus, :lyrics

  # again, can have a boolean for regular vs bonus
  validates :name, :regular_or_bonus, presence: true
  validates :regular_or_bonus, inclusion: { in: %w(bonus regular) }

  has_many :notes, class_name: "Note", primary_key: :id,
    foreign_key: :track_id, dependent: :destroy

  belongs_to(
    :album,
    class_name: "Album",
    primary_key: :id,
    foreign_key: :album_id
  )

  has_one :band, through: :album, source: :band
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @band = Band.find(params[:band_id])
    @album = Album.find(params[:album_id])
    @tracks = @album.tracks
    render :index
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    @band = @track.band
    @notes = @track.notes
    render :show
  end

  def new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(params[:track])
    @track.regular_or_bonus ||= "bonus"

    if @track.save
      # flash message?
      redirect_to bands_url
    else
      # flash message?
      redirect_to :back
    end
  end

  def edit
    @albums = Album.all
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    track = Track.find(params[:id])
    track.update_attributes(params[:track])

    if track.save
      redirect_to bands_url
    else
      redirect_to :back
    end
  end

  def destroy
    track = Track.find(params[:id])

    track.destroy
    redirect_to bands_url
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  def ugly_lyrics(lyrics)
    str = "<pre>"

    lyrics.split("\n").each do |line|
      str << "&#9835 "
      str << h(line)
      str << "\n"
    end

    str << "</pre>"
    str.html_safe
  end
end

app/views/tracks/_change_track.html.erb
<label>
  Track name
  <input type="text" name="track[name]">
</label>
<br>
<br>

<label>
  Album
  <select name="track[album_id]">
    <option value="">Choose an album...</option>
    <% @albums.each do |album| %>
      <option value="<%= album.id %>"><%= album.name%></option>
    <% end %>
  </select>
</label>
<br>
<br>

<label>
  Bonus track?
  <input type="checkbox" name="track[regular_or_bonus]" value = "bonus">
</label>
<br>
<br>

<input type="submit" value="Save track">

app/views/tracks/edit.html.erb
<form action="<%=track_url(@track)%>" method="post">
  <input type="hidden" name="_method" value="PUT">
  <%= render "change_track" %>
</form>

app/views/tracks/index.html.erb
<h2><%= "Tracks on #{@album.name}"%></h2>

<ul>
  <% @tracks.each do |track| %>
    <li>
      <%#= track.name %>
      <%= link_to "#{track.name}", band_album_track_url(@band, @album, track) %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to #{@album.name}'s page", band_album_url(@band, @album) %>
<%= link_to "Back to #{@band.name}'s page", band_url(@band) %>

app/views/tracks/new.html.erb
<form action="<%=tracks_url%>" method="post">
  <%= render "change_track" %>
</form>

app/views/tracks/show.html.erb
<h2><%= @track.name %></h2>
<br>

<h4>About <%=@track.name %></h4>
<p> <%= "#{@track.name} is a #{@track.regular_or_bonus} track on #{@album.name}
  by #{@band.name}."%> </p>
<br>

<h4><%= @track.name%> Lyrics</h4>
<%= ugly_lyrics(@track.lyrics) %>

<% @notes.each do |note| %>
  <%= render "notes/note", note: note%>
  <% if current_user && (current_user.admin || note.user_id == current_user.id) && current_user.active %>
    <%= button_to "Delete this note", track_note_url(@track, note), method: :delete %>
  <% end %>
  <br>
<% end %>

<% if current_user && current_user.active %>
  <%= render "notes/add_note", track: @track %>
<% end %>

<%= link_to "More albums by #{@band.name}", band_albums_url(@band) %>
<br>
<br>

<%= link_to "More tracks on #{@album.name}", band_album_tracks_url(@band, @album) %>
<br>
<br>

<% if current_user && current_user.admin %>
  <%= button_to "Edit this track", edit_track_url(@track), method: :get %>
  <%= button_to "Delete track", track_url(@track), method: :delete %>
<% end %>