config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands do
    resources :albums, only: [:index, :show] do
      resources :tracks, only: [:index, :show]
    end
  end

  resources :albums, except: :index # change
  resources :tracks, except: :index do # change
    resources :notes, only: [:show, :new, :create, :destroy]
  end

  resources :users do
    get "activate"
  end
  resource :session

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :session_token, :password, :admin, :active

  validates :email, :session_token, presence: true
  validates :admin, :active, inclusion: {in: [true, false] }
  before_validation :ensure_session_token #, :ensure_statuses

  has_many :notes, primary_key: :id, foreign_key: :user_id,
    class_name: "Note", dependent: :destroy

  def password=(pw)
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.set_statuses # bad. refactor
    self.save!
  end

  def ensure_session_token
    self.session_token || self.reset_session_token!
    true
  end

  def self.find_by_credentials(email_address, password)
    user = User.find_by_email(email_address)
    return nil unless user.is_password?(password)
    user
  end

  def set_statuses
    self.active = false unless self.active
    self.admin = false unless self.admin
  end

  # def ensure_statuses
#     if self.active.nil?
#       self.active = false
#     end
#
#     if self.admin.nil?
#       self.admin = false
#     end
#
#     true
#   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @user.set_statuses

    if @user.save
      msg = UserMailer.welcome_email(@user, user_activate_url(@user))
      msg.deliver!
      # flash message?
      self.current_user = @user
      redirect_to bands_url
    else
      # flash
      redirect_to :back
    end
  end

  def activate
    @user = User.find(params[:user_id])
    if @user.session_token == session[:session_token]
      @user.active = true
    end
    @user.save
    redirect_to bands_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input name="_method" type="hidden" value="<%= method %>">
  <input name="authenticity_token" type="hidden"
    value="<%= form_authenticity_token %>">

  <label>
    Email address
    <input name="user[email]" type="text">
  </label>
  <br>

  <label>
    Password
    <input name="user[password]" type="password">
  </label>
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", user: @user%>