config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands do
    resources :albums, only: [:index, :show] do
      resources :tracks, only: [:index, :show]
    end
  end

  resources :albums, except: :index # change
  resources :tracks, except: :index do # change
    resources :notes, only: [:show, :new, :create, :destroy]
  end

  resources :users do
    get "activate"
  end
  resource :session

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :band_id, :live_or_studio

  # class hash associating these two values with strings?
  # or just a method
  validates :name, :band_id, :live_or_studio, presence: true
  validates :live_or_studio, inclusion: {in: %w(live studio)}

  belongs_to(
    :band,
    class_name: "Band",
    primary_key: :id,
    foreign_key: :band_id,
    dependent: :destroy
  )

  has_many :tracks, class_name: "Track",
    primary_key: :id, foreign_key: :album_id
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @band = Band.find(params[:band_id])
    @albums = @band.albums

    render :index
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
    @tracks = @album.tracks
    render :show
  end

  def new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(params[:album])
    @album.live_or_studio ||= "studio"

    if @album.save
      # flash message?
      redirect_to bands_url
    else
      # flash message?
      redirect_to :back
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    album = Album.find(params[:id])
    album.update_attributes(params[:album])

    if album.save
      redirect_to bands_url
    else
      redirect_to :back
    end
  end

  def destroy
    album = Album.find(params[:id])

    album.destroy
    redirect_to bands_url
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_change_album.html.erb
<label>
  Album name
  <input type="text" name="album[name]">
</label>
<br>
<br>

<label>
  Band
  <select name="album[band_id]">
    <option value="">Choose a band...</option>
    <% @bands.each do |band| %>
      <option value="<%= band.id %>"><%= band.name%></option>
    <% end %>
  </select>
</label>
<br>
<br>

<label>
  Live album?
  <input type="checkbox" name="album[live_or_studio]" value = "live">
</label>
<br>
<br>

<input type="submit" value="Save album">

app/views/albums/edit.html.erb
<form action="<%=album_url(@album)%>" method="post">
  <input type="hidden" name="_method" value="PUT">
  <%= render "change_album" %>
</form>

app/views/albums/index.html.erb
<h2><%= "#{@band.name}'s Albums" %></h2>

<ul>
  <% @albums.each do |album| %>
    <li>
      <%= album.name %>
    </li>
  <% end %>
</ul>

<%= link_to "Back to #{@band.name}'s page", band_url(@band) %>

app/views/albums/new.html.erb
<form action="<%=albums_url%>" method="post">
  <%= render "change_album" %>
</form>

app/views/albums/show.html.erb
<h2><%= @album.name %></h2>
<br>

<h4>About <%=@album.name %></h4>
<p> <%= "#{@album.name} is a #{@album.live_or_studio} album by #{@band.name}."%> </p>
<br>

<%= link_to "More albums by #{@band.name}", band_url(@band) %>
<br>
<br>

<%= link_to "Tracks on #{@album.name}", band_album_tracks_url(@album.band_id, @album.id) %>
<br>
<br>

<% if current_user && current_user.admin %>
  <%= button_to "Add a track", new_track_url, method: :get %>
  <%= button_to "Edit this album", edit_album_url(@album), method: :get %>
  <%= button_to "Delete album", album_url(@album), method: :delete %>
<% end %>