config/routes.rb
MusicApp::Application.routes.draw do

  resources :bands do
    resources :albums, only: [:index, :show] do
      resources :tracks, only: [:index, :show]
    end
  end

  resources :albums, except: :index # change
  resources :tracks, except: :index do # change
    resources :notes, only: [:show, :new, :create, :destroy]
  end

  resources :users do
    get "activate"
  end
  resource :session

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :albums, class_name: "Album", primary_key: :id,
    foreign_key: :band_id, dependent: :destroy

  has_many :tracks, through: :albums, source: :tracks
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    # can do: @band.includes(:albums).includes(:tracks)
    @band = Band.includes(:albums, :tracks).find(params[:id]) # nest this.
    @albums = @band.albums
    @tracks = @band.tracks
  end

  def new
    render :new
  end

  def create
    band = Band.new(params[:band])

    if band.save
      # add success message to flash?
      redirect_to bands_url
    else
      # add error to flash?
      redirect_to :back
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    band = Band.find(params[:id])
    band.update_attributes(params[:band])

    if band.save
      redirect_to bands_url
    else
      redirect_to :back
    end
  end

  def destroy
    band = Band.find(params[:id])

    band.destroy
    redirect_to bands_url
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_change_band.html.erb
<label>
  Band name
  <input type="text" name="band[name]">
</label>

<input type="submit" value="Save band">

app/views/bands/edit.html.erb
<form action="<%=band_url(@band)%>" method="post">
  <input type="hidden" name="_method" value="PUT">
  <%= render "change_band" %>
</form>

app/views/bands/index.html.erb
<h2>Band list</h2>

<ul>
  <% @bands.each do |band| %>
    <li>
      <%= link_to "#{band.name}", band_url(band) %>
    </li>
  <% end %>
</ul>

<%= button_to "Add band", new_band_url, method: :get%>

app/views/bands/new.html.erb
<form action="<%=bands_url%>" method="post">
  <%= render "change_band" %>
</form>
<!-- put this whole thing inside the partial>

app/views/bands/show.html.erb
<h2><%= @band.name %></h2>
<br>

<h3><%= "#{@band.name}'s Albums"%></h3>
<ul>
  <% @albums.each do |album| %>
  <li>
    <%#= album.name %>
    <%= link_to "#{album.name}", band_album_url(@band, album) %>
  </li>
  <% end %>
</ul>
<br>

<h3><%= "#{@band.name}'s Tracks"%></h3>
<ul>
  <% @tracks.each do |track| %>
  <li>
    <%#= track.name %>
    <%= link_to "#{track.name}", track_url(track) %>
  </li>
  <% end %>
</ul>
<br>

<% if current_user && current_user.admin %>
  <%= button_to "Add album", new_album_url, method: :get%>
  <%= button_to "Edit band", edit_band_url(@band), method: :get %>
  <%= button_to "Delete band", band_url(@band), method: :delete %>
<% end%>
<br>